### PR TITLE
Update bdk dependency to v0.23

### PR DESCRIPTION
**Pull request by rajarshimaitra**
Candidate update for bdk [v0.23.0-rc.1](https://github.com/bitcoindevkit/bdk/releases/tag/v0.23.0-rc.1)

### CODE REVIEW

**Comment by rajarshimaitra** [comment]
@notmandatory, have updated it on bdk v0.23..

**Comment by ulrichard** [comment]
Shouldn't the package version also be updated?

**Comment by rajarshimaitra** [comment]
Yes it should be.. Thanks. updated..

**Review by notmandatory — APPROVED** [review]
ACK e37e08172d1523420bd0fba74742b9935e65f3ad

Thanks for getting this updated!

**Comment by notmandatory** [comment]
Any objections if I also publish the new version of this crate once this PR is merged?

**Comment by rajarshimaitra** [comment]
> Any objections if I also publish the new version of this crate once this PR is merged?

Makes sense to me..

**Pull request merged**
