### PR TITLE
Bump bdk version to 0.24.0

### PR DESCRIPTION
**Pull request by notmandatory**
### Description

Update BDK to the latest version, 0.24.0.

### Notes to the reviewers

I also had to add base64 as a new dev dependency because it's not exported by bdk.

### CODE REVIEW

**Comment by notmandatory** [comment]
This still has some bugs to fix and can't be merged until after bdk 0.24.0 is released.

**Comment by benthecarman** [comment]
Looks like the only failing test is just the error message that slightly changed, this should be able to move forward

**Comment by notmandatory** [comment]
I had to fix a couple things to get tests to pass:
* updated to new Miniscript error string
* according to `bitcoin-cli` and bip173.org the new PSBT data looks like it added a value for `bip32_derivs`, otherwise PSBTs are the same, so updated test with new PSBT.
```
diff psbt-left.txt psbt-right.txt 
73,80c73
<       },
<       "bip32_derivs": [
<         {
<           "pubkey": "032b0558078bec38694a84933d659303e2575dae7e91685911454115bfd64487e3",
<           "master_fingerprint": "ece52657",
<           "path": "m"
<         }
<       ]
---
>       }
```

**Review by ulrichard — APPROVED** [review]
Looks good to me. I also tested with our application, where this is used. All good. Thanks for maintaining this.

**Pull request merged**
